Config = {}

-- Jobs allowed to use the tuning editor and commands (Currently disabled: allowed for everyone)
Config.AllowedJobs = {
    'admin',
    'mechanic'
}

-- List of valid handling attributes in exact order of handling.meta CHandlingData
Config.ValidAttributes = {
    'fMass',
    'fInitialDragCoeff',
    'fDownforceModifier',
    'fPercentSubmerged',
    'vecCentreOfMassOffset_x',
    'vecCentreOfMassOffset_y',
    'vecCentreOfMassOffset_z',
    'vecInertiaMultiplier_x',
    'vecInertiaMultiplier_y',
    'vecInertiaMultiplier_z',
    'fDriveBiasFront',
    'nInitialDriveGears',
    'fInitialDriveForce',
    'fDriveInertia',
    'fClutchChangeRateScaleUpShift',
    'fClutchChangeRateScaleDownShift',
    'fInitialDriveMaxFlatVel',
    'fBrakeForce',
    'fBrakeBiasFront',
    'fHandBrakeForce',
    'fSteeringLock',
    'fTractionCurveMax',
    'fTractionCurveMin',
    'fTractionCurveLateral',
    'fTractionSpringDeltaMax',
    'fLowSpeedTractionLossMult',
    'fCamberStiffnesss',
    'fTractionBiasFront',
    'fTractionLossMult',
    'fSuspensionForce',
    'fSuspensionCompDamp',
    'fSuspensionReboundDamp',
    'fSuspensionUpperLimit',
    'fSuspensionLowerLimit',
    'fSuspensionRaise',
    'fSuspensionBiasFront',
    'fAntiRollBarForce',
    'fAntiRollBarBiasFront',
    'fRollCentreHeightFront',
    'fRollCentreHeightRear',
    'fCollisionDamageMult',
    'fWeaponDamageMult',
    'fDeformationDamageMult',
    'fEngineDamageMult',
    'fPetrolTankVolume',
    'fPetrolConsumptionRate',
    'fOilVolume',
    'fSeatOffsetDistX',
    'fSeatOffsetDistY',
    'fSeatOffsetDistZ',
    'nMonetaryValue',
    'strModelFlags',
    'strHandlingFlags',
    'strDamageFlags',
    
    -- SubHandlingData (CCarHandlingData)
    'fBackEndPopUpCarImpulseMult',
    'fBackEndPopUpBuildingImpulseMult',
    'fBackEndPopUpMaxDeltaSpeed',
    'fToeFront',
    'fToeRear',
    'fCamberFront',
    'fCamberRear',
    'fCastor',
    'fMaxDriveBiasTransfer',
    'fJumpForceScale',
    'fIncreasedRammingForceScale',
    'strAdvancedFlags'
}